language: cpp

# whitelist
branches:
  only:
    - dev

notifications:
  recipients:
    - icaoberg@alumni.cmu.edu
  email:
    on_success: change
    on_failure: always

compiler:
  - gcc

before_install:
    - echo "before_install"
    - sudo apt-get update -qq

script:
    - make all