language: cpp

# whitelist
branches:
  only:
    - dev

compiler:
  - gcc

before_install:
    - echo "before_install"
    - sudo apt-get update -qq
    - make all

scripts:
     - echo "Test svm-train"
     - ./svm-train -s 0 -c 5 -t 2 -g 0.5 -e 0.1 ./heart_scale